language: node_js
install: npm install && npm run build

jobs:
    include:
    - stage: tests
      name: "Unit + Integration Node 6"
      script: npm run test
      node_js: "8"
    - script: npm run test
      name: "Unit + Integration Node 10"
      node_js: "10"
    - script: npm run test
      name: "Unit + Integration Node 11"
      node_js: "11.0.0"

    - script: npm run lint
      name: "Linting"
      node_js: "10"
    - script: npm run coverage
      name: "Coverage"
      node_js: "10"

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MEhhbGYtU2hvdCUzQWhhbGYtc2hvdC51ay8lMjFxUE5PblVzTnNaclRvRlpxeEIlM0FoYWxmLXNob3QudWs"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
