bridge:
  domain: "localhost"
  homeserverUrl: "http://localhost:8008"
auth:
  clientID: "12345" # Get from discord
  secret: "blah"
  botToken: "foobar"
logging:
  level: "warn" #silly, verbose, info, http, warn, error
database:
  filename: "discord.db"
